<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 
Takes the shape of the data that you're passing into your network so columns or features. 

### Hidden Layer: 
Deep learning layer, mysterious and don't interact with them at all.  Hidden because we don't have control.  Process that decides   the optimal weights.   

### Output Layer: 
Key thing that differentiates between regression or classification and based on how the output layer is defined we should be able to understand what the network is outputting. binary classification: sigmoid. Multiclass classification: softmax. Regression: no activation function. 

### Neuron:
A neuron is a mathematical function that takes some inputs, weight them, and then return an output

### Weight:
The weights are some parameters used within the hidden layers to transform the input

### Activation Function:
The activation function transforms the output in a specific format for our context. For example, if we have a binary classification problem, we can set a sigmoid function as activation function to transform the output vector in the probability of having the primary class. We can use different activation functions for different problems to get the output in a format suitable for the problem we are trying to solve.

### Node Map:
A node map is a schema of the neurons, which shows the number of input layers, hidden layers, and output layers, as well as the interaction between them.

### Perceptron:
A perceptron is a simple neuron.

In [ ]:
## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')


In [2]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [3]:
inputs = df.to_numpy()
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [4]:
correct_outputs = [[1], [1], [1], [0]]

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [6]:
import numpy as np

weights = 2 * np.random.random((3,1)) - 1
weights

array([[-0.92324968],
       [-0.39021288],
       [-0.81971926]])

In [7]:
# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-2.41148084]
 [-2.40899919]
 [ 7.49025836]]
Output after training
[[0.99944177]
 [0.99381071]
 [0.99382596]
 [0.00799883]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [8]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
diabetes.describe().transpose()

count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [18]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

#so outcome is our target. since it has been dropped from the feats. 
#why is skin thickness 0.  Thats weird. All the columns have 0 as a min.  This doesn't make sense. 
feats = list(diabetes)[:-1]
print(feats)
y = diabetes['Outcome']

scaler = MinMaxScaler()

X = scaler.fit_transform(diabetes[feats])
X = pd.DataFrame(X, columns = [feats])
X

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']


Pregnancies   Glucose BloodPressure SkinThickness   Insulin       BMI  \
0      0.352941  0.743719      0.590164      0.353535  0.000000  0.500745   
1      0.058824  0.427136      0.540984      0.292929  0.000000  0.396423   
2      0.470588  0.919598      0.524590      0.000000  0.000000  0.347243   
3      0.058824  0.447236      0.540984      0.232323  0.111111  0.418778   
4      0.000000  0.688442      0.327869      0.353535  0.198582  0.642325   
..          ...       ...           ...           ...       ...       ...   
763    0.588235  0.507538      0.622951      0.484848  0.212766  0.490313   
764    0.117647  0.613065      0.573770      0.272727  0.000000  0.548435   
765    0.294118  0.608040      0.590164      0.232323  0.132388  0.390462   
766    0.058824  0.633166      0.491803      0.000000  0.000000  0.448584   
767    0.058824  0.467337      0.573770      0.313131  0.000000  0.453055   

    DiabetesPedigreeFunction       Age  
0                   0.234415  0.483333  
1                   0.116567  0.166667  
2                   0.253629  0.183333  
3                   0.038002  0.000000  
4                   0.943638  0.200000  
..                       ...       ...  
763                 0.039710  0.700000  
764                 0.111870  0.100000  
765                 0.071307  0.150000  
766                 0.115713  0.433333  
767                 0.101196  0.033333  

[768 rows x 8 columns]

In [32]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self,rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1 - sx)

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        weights = 2 * np.random.random((3,1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(inputs, weights)
            # Activate!
            activated_output = sigmoid(weighted_sum)
            # Cac error
            error = correct_outputs - activated_output
            adjustments = error * sigmoid_derivative(weighted_sum)
            # Update the Weights
            weights += np.dot(inputs.T, adjustments)

    def predict(self, X):
    """Return class label after unit step"""
        return np.where(self.weighted_sum(X) >= 0.0, 1, -1)

IndentationError: expected an indented block (<ipython-input-32-0aa23b07ebbf>, line 20)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?